Vagrant.require_version '>= 2.0.2'
require'vagrant-openstack-provider'
require 'yaml'

VAGRANTFILE_API_VERSION = '2'

# Read YAML file with VM details (box, CPU, and RAM)
machines = YAML.load_file(File.join(File.dirname(__FILE__),'environment.yml'))
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.ssh.username = 'ubuntu'
 config.ssh.private_key_path = 'new1.pem'
 config.vm.provider :openstack do |os, override|
   os.identity_api_version = '3'
   os.openstack_auth_url = machines['AUTH_URL']
   os.domain_name = machines['DOMAIN_NAME']
   os.username = machines['USERNAME']
   os.password = machines['PASSWORD']
   os.tenant_name = machines['TENANT_NAME']
   os.project_name = machines['PROJECT_NAME']
   os.keypair_name = machines['KEY_PAIR_NAME']
   os.image = machines['IMAGE']
   os.flavor = machines['FLAVOR']
 end
 config.vm.synced_folder "./file", "/home/ubuntu/docker"
 config.vm.define 'jenkins_server' do |s|
      s.vm.provision 'docker'
      s.vm.provision 'docker_compose', compose_version:'1.23.2'
      s.vm.provision "shell", path: "install.sh"
      s.vm.provider :openstack do |os, override|
       os.server_name = 'AT08-WL-1'
       override.vm.synced_folder '.', '/vagrant', disabled: true
     end
 end
end