# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'vagrant-openstack-provider'
  Vagrant.configure('2') do |config |
    config.ssh.username = 'ubuntu'
    config.ssh.private_key_path = "./new1.pem"
    config.vm.provider :openstack do |os, override |
      os.identity_api_version = '3'
      os.openstack_auth_url = 'http://10.28.3.240:5000/v3'
      os.domain_name = 'fundacion-jala'
      os.username = 'wilsonlopez'
      os.password = ''
      os.tenant_name = '99c2e05a201f4744adc68ef74709dc2f'
      os.project_name = 'fj_wilsonlopez_at08-lab'
      os.keypair_name  = 'new1'
      os.image = 'ubuntu-18.04-amd64-mate_desktop_19122018'
      os.flavor = 'f4.desktop.large'
      os.server_name = 'WL-at08-2'
      override.vm.synced_folder '.', '/vagrant', disabled: true
  end
end