version: '3'
services:
 jenkins_server:
   image: "registry.jala.info/devops/jenkins/jenkins:2.150.3-alpine"
   ports:
     - "8080:8080"
     - "50000:50000"
   volumes:
     - ./jenkins_home:/var/jenkins_home
